apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-policy-test-dep
  namespace: {{ .Values.namespace}}
  labels:
    service: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - pwsh
          - /c
          - echo 'starting';ipconfig /all; curl https://joymon.github.io/Data/Home/whatsnew.json; echo 'going to sleep'; start-sleep -s 600;
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}